[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-s"
testpaths = [
    "tests",
]
filterwarnings = [
    "ignore:Failed to import filter module 'urllib3':pytest.PytestConfigWarning",
    "ignore::urllib3.exceptions.InsecureRequestWarning"
]

[tool.ruff]
required-version = '>=0.5.1'
target-version = 'py38'
[tool.ruff.lint]
extend-select = ["FA"]
